// Package usermessage renders safe Chinese messages at public transport boundaries.
// Internal errors and machine-readable protocol values are deliberately unchanged.
package usermessage

import (
	"fmt"
	"regexp"
	"strings"
)

const Fallback = "操作失败，请稍后重试"

var precisionError = regexp.MustCompile(`^amount must be positive: amount allows at most ([0-9]{1,2}) decimal places$`)

// Chinese only exposes registered public messages. Unknown database/provider
// errors must not leak SQL, credentials, addresses or implementation details.
func Chinese(message string) string {
	if translated, ok := Lookup(message); ok {
		return translated
	}
	return Fallback
}

func Lookup(message string) (string, bool) {
	message = strings.TrimSpace(message)
	if translated, ok := messages[message]; ok {
		return translated, true
	}
	for _, translated := range messages {
		if message == translated {
			return message, true
		}
	}
	if match := precisionError.FindStringSubmatch(message); match != nil {
		return fmt.Sprintf("金额必须大于 0，且最多保留 %s 位小数", match[1]), true
	}
	// Wrapped business errors retain their public reason but never expose an
	// unregistered suffix (which may be raw SQL or user-controlled content).
	parts := strings.SplitN(message, ": ", 2)
	if len(parts) == 2 {
		if prefix, ok := messages[parts[0]]; ok {
			if suffix, known := messages[parts[1]]; known {
				return prefix + "：" + suffix, true
			}
			return prefix, true
		}
	}
	return "", false
}

var messages = map[string]string{
	"后台密码参数无效":                                           "后台密码参数无效",
	"无权管理或使用后台操作密码":                                      "无权管理或使用后台操作密码",
	"该后台操作密码尚未设置，请联系管理员":                                 "该后台操作密码尚未设置，请联系管理员",
	"后台操作密码不正确":                                          "后台操作密码不正确",
	"当前管理员登录密码不正确":                                       "当前管理员登录密码不正确",
	"密码验证失败次数过多，请15分钟后重试":                                "密码验证失败次数过多，请15分钟后重试",
	"后台操作密码服务异常":                                         "后台操作密码服务异常",
	"后台操作密码服务不可用":                                        "后台操作密码服务不可用",
	"仅管理员或运营人员可以操作资金":                                    "仅管理员或运营人员可以操作资金",
	"请求参数无效":                                             "请求参数无效",
	"请输入当前管理员的二级密码":                                      "请输入当前管理员的二级密码",
	"二级密码服务不可用":                                          "二级密码服务不可用",
	"请先登录管理员账号":                                          "请先登录管理员账号",
	"请先设置当前管理员的二级密码":                                     "请先设置当前管理员的二级密码",
	"二级密码错误":                                             "二级密码错误",
	"无法验证二级密码":                                           "无法验证二级密码",
	"资金服务不可用":                                            "资金服务不可用",
	"资金操作失败":                                             "资金操作失败",
	"资金操作参数无效":                                           "资金操作参数无效",
	"请求编号已用于其他资金操作，请勿修改参数后重用":                            "请求编号已用于其他资金操作，请勿修改参数后重用",
	"仅管理员可以操作资金":                                         "仅管理员可以操作资金",
	"金额必须为正数且符合币种精度和余额范围":                                "金额必须为正数且符合币种精度和余额范围",
	"币种不存在或未启用":                                          "币种不存在或未启用",
	"虚拟账户不能下分或人工扣分":                                      "虚拟账户不能下分或人工扣分",
	"可用余额不足":                                             "可用余额不足",
	"request method is not allowed":                      "该接口不支持此请求方法",
	"interface not found":                                "请求的接口不存在",
	"account ID and currency are required":               "请填写账号 ID 和币种",
	"account ID is required":                             "请填写账号 ID",
	"account is banned from betting":                     "该账号已被禁止投注",
	"account is disabled":                                "该账号已被禁用",
	"account is not active":                              "该账号当前不可用",
	"account is required":                                "请填写账号",
	"account_id, chain_code and token_code are required": "请填写账号 ID、链代码和币种代码",
	"activity is unavailable":                            "活动暂不可用",
	"address belongs to another account":                 "该地址不属于当前账号",
	"administrator cannot disable own account":           "管理员不能禁用自己的账号",
	"administrator cannot remove own admin role":         "管理员不能移除自己的管理员角色",
	"agent level must be between 1 and 6":                "代理等级必须在 1 至 6 之间",
	"agent not found":                                    "代理不存在",
	"agent relation already exists":                      "代理关系已存在",
	"agent service is unavailable":                       "代理服务暂不可用",
	"amount must be positive":                            "金额必须大于 0",
	"an administrator already exists":                    "平台已存在管理员",
	"announcement not found":                             "公告不存在",
	"announcement title and body are required, and end time must be after start time": "请填写公告标题和内容，结束时间必须晚于开始时间",
	"announcements are unavailable":        "公告服务暂不可用",
	"asset is not enabled for withdrawal":  "该资产暂不支持提现",
	"at least one task config is required": "至少需要配置一个活动任务",
	"audit logs are unavailable":           "审计日志服务暂不可用",
	"authentication is not configured":     "身份认证尚未配置",
	"authentication is unavailable":        "身份认证服务暂不可用",
	"authentication required":              "请先登录",
	"avatar not found":                     "头像不存在",
	"avatar_url must be empty or a confirmed image upload owned by the current user": "头像必须为空，或使用本人已确认上传的图片",
	"bet belongs to another account":                                                 "该投注不属于当前账号",
	"bet can only be cancelled before betting closes":                                "只能在封盘前取消投注",
	"bet not found":                                                            "投注记录不存在",
	"bets are unavailable":                                                     "投注记录服务暂不可用",
	"betting is closed":                                                        "本期已封盘，无法投注",
	"betting is unavailable":                                                   "投注服务暂不可用",
	"cancel refund would overflow wallet balance":                              "取消投注后的退款金额超出钱包余额上限",
	"cannot consume stamina for another account":                               "不能消耗其他账号的体力",
	"cannot disable the platform's last active admin":                          "不能禁用平台最后一个有效管理员",
	"cannot place bets for another account":                                    "不能替其他账号投注",
	"cannot remove the platform's last admin role":                             "不能移除平台最后一个管理员角色",
	"chain deposit webhook is unavailable":                                     "链上充值回调服务暂不可用",
	"chain withdrawal webhook is unavailable":                                  "链上提现回调服务暂不可用",
	"chat is unavailable":                                                      "聊天服务暂不可用",
	"chat room access denied":                                                  "无权访问该聊天室",
	"chat room not found":                                                      "聊天室不存在",
	"client_request_id is required":                                            "请填写请求唯一标识 client_request_id",
	"commission cannot transition from its current status":                     "当前佣金状态不允许此操作",
	"commission not found":                                                     "佣金记录不存在",
	"commission rate must be between 0 and 10000 basis points":                 "佣金比例必须在 0 至 10000 个基点之间",
	"config key, visibility, or JSON value is invalid":                         "配置键、可见范围或 JSON 配置内容无效",
	"content operation is unsupported by the configured storage":               "当前存储方式不支持此文件操作",
	"credit service is unavailable":                                            "上分服务暂不可用",
	"currency already exists or version is stale":                              "币种已存在或配置版本已过期，请刷新后重试",
	"currency is disabled for new operations":                                  "该币种已停用，不能发起新操作",
	"currency is not registered":                                               "该币种尚未登记",
	"currency is required":                                                     "请选择币种",
	"currency service is unavailable":                                          "币种服务暂不可用",
	"current password is incorrect":                                            "当前密码不正确",
	"deposit address is not registered":                                        "充值地址尚未登记",
	"deposit address not found":                                                "充值地址不存在",
	"deposit address provider is unavailable":                                  "充值地址服务商暂不可用",
	"deposit addresses are unavailable":                                        "充值地址服务暂不可用",
	"deposit history is unavailable":                                           "充值记录服务暂不可用",
	"display_name is required and profile fields are too long":                 "昵称不能为空，且资料字段不能超过长度限制",
	"from and to must be RFC3339 and to must be after from":                    "起止时间必须符合 RFC3339 格式，且结束时间晚于开始时间",
	"game code already exists":                                                 "玩法代码已存在",
	"game name, mode and valid rules are required":                             "请填写游戏名称、模式和有效规则",
	"game room code already exists":                                            "房间代码已存在",
	"game room not found":                                                      "游戏房间不存在",
	"game type and future bet close time are required":                         "请选择玩法，并将封盘时间设置为未来时间",
	"game type is required":                                                    "请选择玩法",
	"game type not found":                                                      "玩法不存在",
	"hash game configuration version conflict":                                 "哈希游戏配置已被修改，请刷新后重试",
	"hash game type not found":                                                 "哈希玩法不存在",
	"hash room and play mode are required":                                     "请选择哈希房间和投注模式",
	"hash rooms, game types, and rounds have a fixed system-managed structure": "哈希房间、玩法和轮次由系统统一维护，不能手动修改结构",
	"identity not found":                                                       "登录身份不存在",
	"insufficient available funds":                                             "可用余额不足",
	"insufficient balance":                                                     "余额不足",
	"insufficient commission balance for reversal":                             "可撤销的佣金余额不足",
	"insufficient points balance":                                              "积分余额不足",
	"insufficient role":                                                        "权限不足",
	"insufficient wallet balance":                                              "钱包余额不足",
	"invalid IP address":                                                       "IP 地址格式不正确",
	"invalid access token":                                                     "登录凭证无效，请重新登录",
	"invalid agent relation":                                                   "代理关系无效",
	"invalid announcement":                                                     "公告配置无效",
	"invalid bet status":                                                       "投注状态无效",
	"invalid commission adjustment":                                            "佣金调整参数无效",
	"invalid currency definition":                                              "币种配置无效",
	"invalid decimal amount":                                                   "金额格式不正确",
	"invalid display amount":                                                   "金额格式或小数位数不正确",
	"invalid game rules":                                                       "游戏规则无效",
	"invalid hash game configuration":                                          "哈希游戏配置无效",
	"invalid leaderboard reward rules":                                         "排行榜奖励规则无效",
	"invalid ledger cursor":                                                    "流水分页游标无效，请重新查询",
	"invalid local object key":                                                 "本地文件标识无效",
	"invalid login name or password":                                           "账号或密码不正确",
	"invalid object key":                                                       "文件标识无效",
	"invalid or expired refresh token":                                         "登录会话无效或已过期，请重新登录",
	"invalid platform config":                                                  "平台配置无效",
	"invalid realtime command":                                                 "实时消息指令格式不正确",
	"invalid red packet request":                                               "红包请求参数无效",
	"invalid request body":                                                     "请求参数格式不正确",
	"invalid round state transition":                                           "当前轮次状态不允许此操作",
	"invalid spin configuration":                                               "转盘配置无效",
	"invalid time range":                                                       "时间范围无效",
	"invalid upload content type or size":                                      "上传文件类型或大小不符合要求",
	"invalid upload request":                                                   "上传请求参数无效",
	"invalid user id":                                                          "用户 ID 无效",
	"invalid virtual account":                                                  "虚拟账号配置无效",
	"invalid webhook api key":                                                  "回调接口密钥无效",
	"invalid webhook signature":                                                "回调签名验证失败",
	"invalid withdrawal address or memo":                                       "提现地址或备注格式不正确",
	"invitation code is invalid":                                               "邀请码无效",
	"invitation code is required and must be valid":                            "请填写有效的邀请码",
	"leaderboard reward rule version conflict":                                 "排行榜奖励配置已被修改，请刷新后重试",
	"leaderboards are unavailable":                                             "排行榜服务暂不可用",
	"ledger belongs to another account":                                        "该流水不属于当前账号",
	"ledger service is unavailable":                                            "流水服务暂不可用",
	"limit must be between 1 and 100":                                          "每页数量必须在 1 至 100 之间",
	"login name is already taken":                                              "该账号名称已被使用",
	"login name must be 3-32 chars of letters, digits, '-' or '_'":             "账号名称须为 3 至 32 位，只能包含字母、数字、短横线或下划线",
	"login_name and password are required":                                     "请填写账号和密码",
	"login_name, password and invitation_code are required":                    "请填写账号、密码和邀请码",
	"logout is unavailable":                                                    "退出登录服务暂不可用",
	"message must contain 1-2000 characters":                                   "消息内容须为 1 至 2000 个字符",
	"missing or invalid access token":                                          "登录凭证缺失或无效，请重新登录",
	"missing required bet fields":                                              "请填写完整的投注参数",
	"missing required fields":                                                  "缺少必填参数",
	"offset must be zero or greater":                                           "分页偏移量不能小于 0",
	"only one hash rate room may be used in the same round":                    "同一期只能选择一个赔率房间投注",
	"origin is not allowed":                                                    "当前访问来源不被允许",
	"outcome contains values outside the game rules pool":                      "开奖结果包含规则范围之外的值",
	"outcome must contain at least one value":                                  "开奖结果至少需要一个值",
	"outcomes must not be empty":                                               "结果选项不能为空",
	"outcomes must not contain duplicates":                                     "结果选项不能重复",
	"outcomes must not contain empty values":                                   "结果选项不能包含空值",
	"payout_divisor must not be negative":                                      "赔率除数不能为负数",
	"payout_multiplier must be positive":                                       "赔率倍数必须大于 0",
	"result_count must be between 1 and the outcome pool size":                 "结果数量必须在 1 至可选结果总数之间",
	"rules must not be empty":                                                  "规则不能为空",
	"invalid bet limit":                                                        "投注限额无效",
	"parent user not found":                                                    "上级用户不存在",
	"password changes are unavailable":                                         "密码修改服务暂不可用",
	"password must contain at least 12 characters":                             "密码至少需要 12 个字符",
	"password verification failed":                                             "密码验证失败",
	"payout would overflow the wallet balance":                                 "派奖金额超出钱包余额上限",
	"period must be today, yesterday, this_week, or last_week":                 "排行周期请选择今天、昨天、本周或上周（today、yesterday、this_week、last_week）",
	"platform config not found":                                                "平台配置不存在",
	"platform config version conflict":                                         "平台配置已被修改，请刷新后重试",
	"platform configs are unavailable":                                         "平台配置服务暂不可用",
	"player_type must be all, real, or virtual":                                "玩家类型请选择全部、真实或虚拟玩家（all、real、virtual）",
	"point withdrawal cannot transition from its current status":               "当前清退状态不允许此操作",
	"point withdrawal not found":                                               "积分清退记录不存在",
	"provider assets are unavailable":                                          "服务商资产列表暂不可用",
	"red packet already claimed":                                               "您已领取过该红包",
	"red packet amount, count, currency, or request ID is invalid":             "红包金额、份数、币种或请求标识无效",
	"red packet claim would overflow wallet":                                   "领取红包后的金额超出钱包余额上限",
	"red packet is exhausted, refunded, or expired":                            "红包已领完、已退回或已过期",
	"red packet not found":                                                     "红包不存在",
	"red packet refund would overflow wallet":                                  "红包退款金额超出钱包余额上限",
	"red packets are unavailable":                                              "红包服务暂不可用",
	"refresh_token is required":                                                "缺少刷新凭证 refresh_token",
	"registration is unavailable":                                              "注册服务暂不可用",
	"request_id is required":                                                   "请填写请求唯一标识 request_id",
	"roles must contain one or more of player, operator, or admin":             "请至少选择玩家、运营或管理员中的一个角色（player、operator、admin）",
	"room name and game kind are required":                                     "请填写房间名称和游戏类别",
	"round cancellation is unavailable":                                        "轮次取消服务暂不可用",
	"round not found":                                                          "轮次不存在",
	"rounds are unavailable":                                                   "轮次服务暂不可用",
	"secondary password is already set; verify the current secondary password to change it": "已设置二级密码，修改时请提供当前二级密码",
	"secondary password is incorrect":                                         "二级密码不正确",
	"secondary password is not set":                                           "尚未设置二级密码",
	"secondary passwords are unavailable":                                     "二级密码服务暂不可用",
	"secondary_password is required":                                          "请填写二级密码",
	"selection is not available for this play":                                "该投注选项不适用于当前玩法",
	"selection must be valid JSON":                                            "投注选项必须是有效的 JSON 数据",
	"sender cannot claim own red packet":                                      "不能领取自己发送的红包",
	"session refresh is unavailable":                                          "会话刷新服务暂不可用",
	"settled hash round has invalid outcome":                                  "已结算哈希轮次的开奖结果无效",
	"settlement outcome does not match the finalized round":                   "结算结果与最终开奖结果不一致",
	"stake is outside the configured play limits":                             "投注金额超出当前玩法限额",
	"stake must be positive":                                                  "投注金额必须大于 0",
	"task config not found":                                                   "活动任务不存在",
	"task currencies must be non-empty and threshold/reward must be positive": "活动任务币种不能为空，累计门槛和奖励金额必须大于 0",
	"task has not reached its claim threshold today":                          "今日尚未达到该任务的领取条件",
	"task reward has already been claimed today":                              "今日已领取该任务奖励",
	"task service is unavailable":                                             "活动任务服务暂不可用",
	"text messages are required":                                              "请发送文本消息",
	"too many login attempts; try again later":                                "登录尝试过于频繁，请稍后重试",
	"trend limit must be between 1 and 200":                                   "走势查询数量必须在 1 至 200 之间",
	"unsupported platform currency":                                           "不支持该平台币种",
	"upload authorization expired":                                            "上传授权已过期，请重新申请",
	"upload is not confirmed":                                                 "文件尚未确认上传",
	"upload not found":                                                        "上传记录不存在",
	"uploaded object content does not match declared type":                    "上传内容与声明的文件类型不一致",
	"uploaded object does not match declared metadata":                        "上传文件与声明信息不一致",
	"uploaded object size does not match authorization":                       "上传文件大小与授权大小不一致",
	"uploads are unavailable":                                                 "上传服务暂不可用",
	"user not found":                                                          "用户不存在",
	"user status must be active, disabled, or bet_banned":                     "用户状态须为正常、禁用或禁止投注（active、disabled、bet_banned）",
	"user_id, amount_minor, activity_id are required":                         "请填写用户 ID、消耗金额和活动 ID",
	"user_id, currency, amount, request_id are required":                      "请填写用户 ID、币种、金额和请求唯一标识",
	"virtual accounts cannot withdraw":                                        "虚拟账号不能下分或提现",
	"wallet belongs to another account":                                       "该钱包不属于当前账号",
	"wallet not found":                                                        "钱包不存在",
	"wallets are unavailable":                                                 "钱包服务暂不可用",
	"webhook timestamp outside allowed window":                                "回调时间戳已超出允许范围",
	"withdrawal amount exceeds the daily limit":                               "提现金额超出每日限额",
	"withdrawal amount exceeds the per-request limit":                         "提现金额超出单笔限额",
	"withdrawal amount is below the minimum":                                  "提现金额低于最低限额",
	"withdrawal belongs to another account":                                   "该提现记录不属于当前账号",
	"withdrawal cannot transition from its current status":                    "当前提现状态不允许此操作",
	"withdrawal not found":                                                    "提现记录不存在",
	"withdrawal provider is unavailable":                                      "提现服务商暂不可用",
	"withdrawals are unavailable":                                             "提现服务暂不可用",
	"client is too slow":                                                      "客户端接收消息过慢，连接已关闭",
	"write failed":                                                            "消息发送失败，连接已关闭",
	"ping failed":                                                             "心跳检测失败，连接已关闭",
	"server shutdown":                                                         "服务正在重启，连接已关闭",
	"closed":                                                                  "连接已关闭",
	"unable to apply withdrawal status":                                       "更新提现状态失败",
	"unable to approve withdrawal":                                            "审批提现失败",
	"unable to authorize upload":                                              "获取上传授权失败",
	"unable to bind agent":                                                    "绑定代理失败",
	"unable to cancel bet":                                                    "取消投注失败",
	"unable to cancel round":                                                  "取消轮次失败",
	"unable to change password":                                               "修改密码失败",
	"unable to claim task reward":                                             "领取任务奖励失败",
	"unable to consume stamina":                                               "消耗体力失败",
	"unable to create announcement":                                           "创建公告失败",
	"unable to create deposit address":                                        "创建充值地址失败",
	"unable to create round":                                                  "创建轮次失败",
	"unable to create virtual account":                                        "创建虚拟账号失败",
	"unable to credit deposit":                                                "充值入账失败",
	"unable to grant commission":                                              "发放佣金失败",
	"unable to list announcements":                                            "查询公告列表失败",
	"unable to list audit logs":                                               "查询审计日志失败",
	"unable to list bet tasks":                                                "查询投注任务失败",
	"unable to list bets":                                                     "查询投注列表失败",
	"unable to list chat rooms":                                               "查询聊天室列表失败",
	"unable to list commissions":                                              "查询佣金列表失败",
	"unable to list currencies":                                               "查询币种列表失败",
	"unable to list deposits":                                                 "查询充值记录失败",
	"unable to list game rooms":                                               "查询游戏房间失败",
	"unable to list game types":                                               "查询玩法列表失败",
	"unable to list hash menus":                                               "查询哈希游戏菜单失败",
	"unable to list leaderboard":                                              "查询排行榜失败",
	"unable to list leaderboard reward rules":                                 "查询排行榜奖励规则失败",
	"unable to list leaderboard rewards":                                      "查询排行榜奖励记录失败",
	"unable to list ledger":                                                   "查询资金流水失败",
	"unable to list platform configs":                                         "查询平台配置失败",
	"unable to list point withdrawals":                                        "查询积分清退记录失败",
	"unable to list public bets":                                              "查询公开投注列表失败",
	"unable to list refunds and clearances":                                   "查询退款和清退明细失败",
	"unable to list roles":                                                    "查询角色列表失败",
	"unable to list rounds":                                                   "查询轮次列表失败",
	"unable to list spins":                                                    "查询转盘列表失败",
	"unable to list task configs":                                             "查询任务配置失败",
	"unable to list users":                                                    "查询用户列表失败",
	"unable to list withdrawals":                                              "查询提现列表失败",
	"unable to load current bets":                                             "查询当前投注失败",
	"unable to load current user":                                             "查询当前用户资料失败",
	"unable to load dashboard":                                                "加载统计看板失败",
	"unable to load hash configuration":                                       "加载哈希游戏配置失败",
	"unable to load hash trends":                                              "加载哈希走势失败",
	"unable to load login IPs":                                                "查询登录 IP 记录失败",
	"unable to load monitor":                                                  "加载监控数据失败",
	"unable to load round countdowns":                                         "加载区块倒计时失败",
	"unable to load round state":                                              "加载轮次状态失败",
	"unable to login":                                                         "登录失败，请稍后重试",
	"unable to logout":                                                        "退出登录失败",
	"unable to open customer service room":                                    "打开客服会话失败",
	"unable to place bet":                                                     "投注失败，请稍后重试",
	"unable to play lucky spin":                                               "参与转盘失败",
	"unable to process chat request":                                          "处理聊天请求失败",
	"unable to send chat message":                                             "发送聊天消息失败",
	"unable to process credit":                                                "上分失败，请稍后重试",
	"unable to process red packet":                                            "处理红包请求失败",
	"unable to read agent relation":                                           "查询代理关系失败",
	"unable to read avatar":                                                   "读取头像失败",
	"unable to read balances":                                                 "查询余额失败",
	"unable to read bet":                                                      "查询投注详情失败",
	"unable to read deposit address":                                          "查询充值地址失败",
	"unable to read platform config":                                          "读取平台配置失败",
	"unable to read points ledger":                                            "查询积分流水失败",
	"unable to read provider assets":                                          "查询服务商资产失败",
	"unable to read request body":                                             "读取请求参数失败",
	"unable to read round":                                                    "查询轮次详情失败",
	"unable to read stamina ledger":                                           "查询体力流水失败",
	"unable to read team summary":                                             "查询团队统计失败",
	"unable to read upload":                                                   "读取上传文件失败",
	"unable to read wallet balance":                                           "查询钱包余额失败",
	"unable to read withdrawal":                                               "查询提现详情失败",
	"unable to refresh session":                                               "刷新登录会话失败，请重新登录",
	"unable to register":                                                      "注册失败，请稍后重试",
	"unable to reject withdrawal":                                             "驳回提现失败",
	"unable to replace leaderboard reward rules":                              "保存排行榜奖励规则失败",
	"unable to request point withdrawal":                                      "申请积分清退失败",
	"unable to request withdrawal":                                            "申请提现失败",
	"unable to reverse commission":                                            "撤销佣金失败",
	"unable to review point withdrawal":                                       "审核积分清退失败",
	"unable to save currency":                                                 "保存币种配置失败",
	"unable to save game room":                                                "保存游戏房间失败",
	"unable to save game type":                                                "保存玩法失败",
	"unable to set agent level":                                               "设置代理等级失败",
	"unable to set commission rate":                                           "设置佣金比例失败",
	"unable to store upload":                                                  "保存上传文件失败",
	"unable to update announcement":                                           "更新公告失败",
	"unable to update hash configuration":                                     "更新哈希游戏配置失败",
	"unable to update platform config":                                        "更新平台配置失败",
	"unable to update profile":                                                "修改用户资料失败",
	"unable to update secondary password":                                     "修改二级密码失败",
	"unable to update user roles":                                             "修改用户角色失败",
	"unable to update user status":                                            "修改用户状态失败",
	"unable to update virtual automation":                                     "修改虚拟账号挂机配置失败",
	"unable to verify secondary password":                                     "验证二级密码失败",
	"unable to verify upload":                                                 "确认上传文件失败",
}
